services:
  - type: web
    name: akktivate-backend
    runtime: node
    rootDir: backend
    buildCommand: npm install && npm rebuild better-sqlite3 --build-from-source && node seed.js
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        value: akktivate_secreto_xK9mP2qL8nR4wZ7vT1jY5bH6cF3sD0eA
      - key: GEMINI_API_KEY
        sync: false
      - key: GROQ_API_KEY
        sync: false
      - key: RESEND_API_KEY
        sync: false
